on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [ opened, reopened, synchronize, edited ]

jobs:
  format:
    name: Ruff format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Format with Ruff
        run: |
          ruff format --check .

  linter:
    name: Ruff linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mujoco --pre -f https://py.mujoco.org/
          pip install warp-lang --pre --upgrade -f https://pypi.nvidia.com/warp-lang/
          pip install -e .[dev,cpu]
      - name: Test with pytest
        run: |
          pytest

  kernel_analyzer:
    name: Kernel analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mujoco --pre -f https://py.mujoco.org/
          pip install warp-lang --pre --upgrade -f https://pypi.nvidia.com/warp-lang/
          pip install -e .[dev,cpu]
      - name: Run kernel analyzer
        run: |
          python contrib/kernel_analyzer/kernel_analyzer/cli.py mujoco_warp/_src/*.py --output=github
